const mongoose = require('mongoose');

const invoiceTemplateSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  isDefault: {
    type: Boolean,
    default: false
  },
  headerLogo: String,
  footerText: String,
  companyDetails: {
    name: String,
    address: String,
    taxId: String,
    contactInfo: String
  },
  templateHtml: {
    type: String,
    required: true
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

// Ensure only one default template at a time
invoiceTemplateSchema.pre('save', async function(next) {
  if (this.isDefault && this.isModified('isDefault')) {
    await mongoose.models.InvoiceTemplate.updateMany(
      { _id: { $ne: this._id } },
      { isDefault: false }
    );
  }
  next();
});

// Create a default template if none exists
invoiceTemplateSchema.statics.createDefaultTemplate = async function() {
  const count = await this.countDocuments();
  
  if (count === 0) {
    const defaultTemplate = {
      name: 'Default Invoice Template',
      isDefault: true,
      headerLogo: '',
      footerText: 'Thank you for your business',
      companyDetails: {
        name: 'ONSITE ATLAS',
        address: '123 Event Street, Conference City',
        taxId: 'TAX-ID-12345',
        contactInfo: 'support@onsiteatlas.com'
      },
      templateHtml: `
        <div class="invoice-template">
          <div class="header">
            {{#if headerLogo}}
              <img src="{{headerLogo}}" alt="{{companyDetails.name}}" />
            {{else}}
              <h1>{{companyDetails.name}}</h1>
            {{/if}}
          </div>
          
          <div class="invoice-details">
            <h2>INVOICE</h2>
            <p><strong>Invoice #:</strong> {{invoiceNumber}}</p>
            <p><strong>Date:</strong> {{invoiceDate}}</p>
            <p><strong>Due Date:</strong> {{dueDate}}</p>
          </div>
          
          <div class="company-details">
            <p><strong>From:</strong></p>
            <p>{{companyDetails.name}}</p>
            <p>{{companyDetails.address}}</p>
            <p><strong>Tax ID:</strong> {{companyDetails.taxId}}</p>
            <p>{{companyDetails.contactInfo}}</p>
          </div>
          
          <div class="client-details">
            <p><strong>To:</strong></p>
            <p>{{client.name}}</p>
            <p>{{client.email}}</p>
            <p>{{client.organization}}</p>
            <p>{{client.address}}</p>
          </div>
          
          <table class="items-table">
            <thead>
              <tr>
                <th>Description</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              {{#each items}}
                <tr>
                  <td>{{name}}</td>
                  <td>{{quantity}}</td>
                  <td>{{currency}} {{unitPrice}}</td>
                  <td>{{currency}} {{totalPrice}}</td>
                </tr>
              {{/each}}
            </tbody>
            <tfoot>
              <tr>
                <td colspan="3" class="text-right"><strong>Subtotal</strong></td>
                <td>{{currency}} {{subtotal}}</td>
              </tr>
              {{#if tax}}
                <tr>
                  <td colspan="3" class="text-right"><strong>Tax ({{taxRate}}%)</strong></td>
                  <td>{{currency}} {{tax}}</td>
                </tr>
              {{/if}}
              <tr>
                <td colspan="3" class="text-right"><strong>Total</strong></td>
                <td>{{currency}} {{total}}</td>
              </tr>
            </tfoot>
          </table>
          
          <div class="footer">
            <p>{{footerText}}</p>
            <p>Generated by ONSITE ATLAS</p>
          </div>
        </div>
      `
    };
    
    await this.create(defaultTemplate);
  }
};

const InvoiceTemplate = mongoose.model('InvoiceTemplate', invoiceTemplateSchema);

module.exports = InvoiceTemplate; 